name: ottobot-update

on:
  pull_request_review:
    types: [submitted]

jobs:
  update-pr:
    if: ${{ github.event.review.state == 'changes_requested' && startsWith(github.event.pull_request.head.ref, 'ottobot-') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - run: git merge origin/main

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Cache aider files
        uses: actions/cache@v4
        with:
          path: |
            .github/ottobot/cache
            .aider.tags.cache.v3
          key: ${{ runner.os }}-ottobot-${{ github.event.pull_request.head.ref }}

      - name: Run ottobot/update script with review comment
        run: ./.github/ottobot/update.sh "${{ github.event.review.body }}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Run compile-readmes script and commit changes
        run: |
          ./scripts/compile-readmes
          git add .
          git diff --quiet && git commit -m "Compile updated READMEs" || echo "No changes to commit."

      - run: git push origin
